// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMiYP0RCmWpf3IE92yH2_3q48z1aUyrrc',
    appId: '1:385141491666:android:93ec50587ffac224726a0b',
    messagingSenderId: '385141491666',
    projectId: 'slack-game-dev-001-6a103',
    storageBucket: 'slack-game-dev-001-6a103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9uQxTa-IxJ2hS4PWBZNO9zqDs7nZJBY',
    appId: '1:385141491666:ios:49fccdefc4e1d0d1726a0b',
    messagingSenderId: '385141491666',
    projectId: 'slack-game-dev-001-6a103',
    storageBucket: 'slack-game-dev-001-6a103.firebasestorage.app',
    iosBundleId: 'com.example.slackGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFkTKIzMu7i7iwMe4lEHCshlcj6VxxPC4',
    appId: '1:385141491666:web:e572effdd3dbaec2726a0b',
    messagingSenderId: '385141491666',
    projectId: 'slack-game-dev-001-6a103',
    authDomain: 'slack-game-dev-001-6a103.firebaseapp.com',
    storageBucket: 'slack-game-dev-001-6a103.firebasestorage.app',
    measurementId: 'G-40MY7YM87G',
  );
}
